version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - api

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE=/api
    depends_on:
      - api

  registry:
    image: python:3.11-slim
    working_dir: /app
    command: python -m http.server 9000 --directory /app/data/state
    volumes:
      - ./data:/app/data
    ports:
      - '9000:9000'
